#!/bin/bash

usage() {
    echo "Usage: sn [-f filename] note_text"
    echo "    -f: Name the file that the note will be saved in."
    echo "    If -f option is not used, the filename will be the current date in the format yyyy-mm-dd."
}

# Parse command-line arguments
filename="$(date +%Y-%m-%d).md"
while getopts "f:" opt; do
    case "$opt" in
        f) filename="$OPTARG.md";;
        *) usage; exit 1;;
    esac
done
shift $((OPTIND-1))

# Check if a note was provided
if [ "$#" -lt 1 ]; then
    usage
    exit 1
fi

# Create the notes directory if it doesn't exist
mkdir -p "$HOME/quick-notes"

# Save the note to the specified file
echo "$@" >> "$HOME/quick-notes/$filename"
echo "Note saved to $HOME/quick-notes/$filename"

